-- AlterTable
ALTER TABLE `Result` MODIFY `item0` INTEGER NULL,
    MODIFY `item1` INTEGER NULL,
    MODIFY `item2` INTEGER NULL,
    MODIFY `item3` INTEGER NULL,
    MODIFY `item4` INTEGER NULL,
    MODIFY `item5` INTEGER NULL,
    MODIFY `item6` INTEGER NULL,
    MODIFY `item7` INTEGER NULL,
    MODIFY `item8` INTEGER NULL,
    MODIFY `item9` INTEGER NULL;
